# Generated by Django 4.1.2 on 2022-10-04 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(help_text='Forename / First Name', max_length=20)),
                ('surname', models.CharField(help_text='Surname / Last Name', max_length=30)),
                ('birthday', models.DateField()),
                ('deceased', models.BooleanField(default=False)),
                ('deathDay', models.DateField(blank=True, null=True)),
                ('pro_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('about', models.CharField(max_length=500, null=True)),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_father', to='living_room.person')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_of_mother', to='living_room.person')),
                ('spouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spouse_of', to='living_room.person')),
            ],
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='living_room.person')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Memory', to='living_room.person')),
            ],
        ),
    ]
